### ISSUE TITLE
%voteissue%

### ISSUE THREAD

**Issue by garfielfing** [mcolour/colourhud#10]
Votes are coming up as blank/missing text in some situations. It's hard to tell what's causing it.

**Comment by mcolour** [comment]
I've tested the vote panel. Here are the results:
Autobalance:
![autobalance](https://github.com/mcolour/colourhud/assets/110155156/a612e415-9495-4917-be15-25fd3c8aee2f)
Kick:
![kick](https://github.com/mcolour/colourhud/assets/110155156/1345a08a-4e5f-4001-bb17-9f7efdc689ab)
Team scramble:
![scramble](https://github.com/mcolour/colourhud/assets/110155156/412552ce-ef4b-48b7-8973-24f2d41a5111)
Extend level:
![extendlevel](https://github.com/mcolour/colourhud/assets/110155156/fda1824f-9dd0-4641-8079-059095ee3e64)
Set map:
![mapset](https://github.com/mcolour/colourhud/assets/110155156/bbe063fe-d80e-4dd8-86c9-35d71f863306)
Change map:
![mapchange](https://github.com/mcolour/colourhud/assets/110155156/cb8cdcb1-fac4-46ee-95d7-a9654ba3a324)
Restart map:
![restartgame](https://github.com/mcolour/colourhud/assets/110155156/c3c83b94-0bce-483b-8807-0fe046840089)

The problem of vote issues missing might be server's fault
