### ISSUE TITLE
Broken round summary in mvm 

### ISSUE THREAD

**Issue by Jacob1Tm** [mcolour/colourhud#14]
![image](https://github.com/mcolour/colourhud/assets/84023677/82e595a4-3999-4d05-993a-0dc08b67ccae)

**Comment by mcolour** [comment]
TF2 is buggy when it comes to placeholder names (like `%killername%`). I tried to "fix" it, by making the file, responsible for rendering MVM wave summary, have the same structure as the TF2 default HUD's one.
