### ISSUE TITLE
Chat can overlap with engineer's building hud

### ISSUE THREAD

**Issue by Pyogenics** [mcolour/colourhud#16]
If you're playing engineer and the game chat fills up then some messages spill onto the sentry health and ammo box.
![image](https://github.com/mcolour/colourhud/assets/82675800/c6b17ecc-c4e4-47e7-bc14-1b35ac0e3fcd)

**Comment by mcolour** [comment]
Fixed it. TF2 only updates the position of the building hud with the hud reload command. Creating anchors solved the problem
