### ISSUE TITLE
Explosions not appearing?

### ISSUE THREAD

**Issue by spectywecty** [mcolour/colourhud#3]
Using this HUD seems to not make explosions show up. Rocket, grenade and sticky explosions do not appear at all, at first I thought it was my custom explosion fx mod but even after taking it out it seems to not be the case.

**Comment by mcolour** [comment]
Go to hud's root folder, then navigate to the scripts folder. Delete the following files in that folder: tf_weapon_cannon.txt tf_weapon_grenadelauncher.txt tf_weapon_particle_cannon.txt tf_weapon_pipebomblauncher.txt tf_weapon_rocketlauncher.txt tf_weapon_rocketlauncher_airstrike.txt tf_weapon_rocketlauncher_directhit.txt
