### ISSUE TITLE
How to see round counter during KOTH games

### ISSUE THREAD

**Issue by Jercer36** [mcolour/colourhud#4]
I noticed that the round counter is not visible when playing in a KOTH game.  Is there a way to make that visible?

**Comment by mcolour** [comment]
Not yet. I'm planning on adding round counters in 2.1 update. For now you can view the counter through the tab menu. Sorry for the trouble :/

**Comment by mcolour** [comment]
Took me a while but I've finally added the round counter. Enjoy the HUD!
