### ISSUE TITLE
Colorhud overrides mastercomfig settings

### ISSUE THREAD

**Issue by garfielfing** [mcolour/colourhud#5]
Running this HUD with Mastercomfig, the network settings from that are overridden, like changes to lerp, interp, rate, and so on. Removing this HUD fixes the issue.

**Comment by garfielfing** [comment]
Tested further, Mastercomfig doesn't load _at all_ with this HUD enabled. It never activates.

**Comment by mcolour** [comment]
Fixed the issue. Now mastercomfig loads.
