### ISSUE TITLE
Mastercomfig isn't loading with this HUD enabled

### ISSUE THREAD

**Issue by garfielfing** [mcolour/colourhud#6]
Mastercomfig still doesn't load with Colourhud, even with the latest update.

**Comment by mcolour** [comment]
That's weird. It loads on my end. Can you elaborate, please?
![screen](https://github.com/mcolour/colourhud/assets/110155156/1ae73156-ac73-4501-b3d4-2b0a05bf2b34)

**Comment by garfielfing** [comment]
My bad, was using the version from mastercomfig's HUDs section. It might still be the old version. Using the newest one from here and it works fine.

**Comment by mcolour** [comment]
That's ok, happens to everyone. Glad to hear that it works fine. Enjoy the HUD!
