### ISSUE TITLE
Broken Scoreboard

### ISSUE THREAD

**Issue by Jacob1Tm** [mcolour/colourhud#7]
a bit unusable...
![06August2023_2192](https://github.com/mcolour/colourhud/assets/84023677/abb4b9d8-12af-489f-9a99-0da45e87a7b6)

**Comment by Jacob1Tm** [comment]
Also, this is kinda cut off
![06August2023_2193](https://github.com/mcolour/colourhud/assets/84023677/53f59264-42d1-4deb-b231-b6671e31fcec)
and cloak with min mode
![06August2023_2194](https://github.com/mcolour/colourhud/assets/84023677/cc5f5caa-b61e-4acf-ad6d-7d120bb7c1ca)

**Comment by mcolour** [comment]
Hmm... Can I see the console log when the button in the hud customization menu is pressed?

**Comment by Jacob1Tm** [comment]
> Hmm... Can I see the console log when the button in the hud customization menu is pressed?

funny thing... that fixed everything... i mean clicking anything in customization menu.

**Comment by mcolour** [comment]
Yeah, during testing I forgot that the hud will look like crap if a person installs it for the first time and doesn't press anything in the hud edit panel. Working on it
