### ISSUE TITLE
Hitmarkers

### ISSUE THREAD

**Issue by AaRCaT** [mcolour/colourhud#8]
I want add hitmarker + animation in your hud, Please

**Comment by mcolour** [comment]
As an example I've downloaded the following hitmarker: https://gamebanana.com/mods/25161
1. Extract the contents of the downloaded hitmarker mod into the HUD's root directory.
2. Go to HUD's root folder, then open the "scripts" folder. There you will find a file called "hudlayout.res". Open it with any text editor.
3. Add the following after the first curly bracket in the file (don't forget to save the file, pls):

	"Hitmarker"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"			"Hitmarker"
		"xpos"				"cs-0.5"
		"ypos"				"cs-0.5"
		"zpos"				"20"
		"wide"				"10"
		"tall"				"10"
		"enabled"			"1"
		"visible"			"1"
		"image"				"replay/thumbnails/hitmarker_red"
		"scaleImage"		"1"
		"Alpha"				"0"
		"teambg_2"			"replay/thumbnails/hitmarker_red"
		"teambg_3"			"replay/thumbnails/hitmarker_blue"
	}

4. In the "scripts" folder navigate to the "hudanimations" and open "misc.txt". In that file you will find the following:

event DamagedPlayer
{
	StopEvent HitMarker 0.0
	RunEvent HitMarker 0.01
}
event HitMarker
{
	Animate "Knuckles Crosshairs"    	 		FgColor     "255 100 100 255"   				Linear 	0.0 	0.00001
	Animate "Knuckles Crosshairs"    			FgColor     "255 255 255 255"   				Linear 	0.10 	0.10001
}

Replace it with the following:

event HitMarker
{

	Animate	Hitmarker	Alpha	"255"	Linear 0.0 0.0		// tcHitmarker start
	Animate	Hitmarker	Alpha	"0"		Linear 0.0 0.95 	// tcHitmarker end

}
event DamagedPlayer
{
	StopEvent 	HitMarker 	0.0
	RunEvent 	HitMarker	0.01
}

5. And you are done. Most hitmarker mods follow the same installation process so you should be fine. One thing I should note is that you are recommended to check the name of hitmarker materials (.vtf and .vmt files). If their name is not hitmarker_red and hitmarker_blue, then change "image", "teambg_2", "teambg_3" parameters in the hudlayout.res file to match the names of material names (if hitmarker doesn't have team variant, then "teambg_2" and "teambg_3" should be the same).

**Comment by AaRCaT** [comment]
Worked, thank you!
