### ISSUE TITLE
Issues/bug Comp

### ISSUE THREAD

**Issue by AaRCaT** [mcolour/colourhud#9]
I found issues/bug from Comp.
1. 6 players in one slot at Team toggle ready
![Screenshot (98)](https://github.com/mcolour/colourhud/assets/27895684/15595a58-c02b-4122-bb7b-729ebcd0ad75)
2. Small icon rank in bottom? When finished match
![Screenshot (99)](https://github.com/mcolour/colourhud/assets/27895684/509f9661-3b8f-4af4-a781-6e08dd5a91db)

**Comment by mcolour** [comment]
Well, for some reason I can't find a competitive match. If you can record a demo of you playing comptetitive and send it to me, then maybe I can do something about it.

**Comment by AaRCaT** [comment]
I found this file: hudtournament.res (i was copy from other hud to your hud)
location folder: ...custom\hudname\resource\ui
![Screenshot (100)](https://github.com/mcolour/colourhud/assets/27895684/1519bb3b-cf0e-45c1-a357-579df74c84ce)


Also how i send demo?

**Comment by mcolour** [comment]
Drag the demo file to the text box. And thank you for finding the file, which is responsible for the comp bug.

**Comment by AaRCaT** [comment]
I cant send Demo file, Sorry
![image](https://github.com/mcolour/colourhud/assets/27895684/3457fbe5-b89f-47c9-99fd-0b50184dd210)

**Comment by mcolour** [comment]
You can upload the demo on mediafire and share the link to it here

**Comment by AaRCaT** [comment]
There (I never use mediafire)
https://drive.google.com/file/d/1Qt2llbW97aEPr27djh9ZZgZ6ffPia6WV/view

**Comment by mcolour** [comment]
Try this

[hudtournament.txt](https://github.com/mcolour/colourhud/files/12304744/hudtournament.txt)

(don't forget to rename it to hudtournament.res)

**Comment by AaRCaT** [comment]
Yeah works,
![Screenshot (101)](https://github.com/mcolour/colourhud/assets/27895684/35fcdf61-e613-41ab-bbde-01077cab097b)
So, you know how scale up rank in match end?

**Comment by mcolour** [comment]
Nope :( Match summary can't be seen properly through demos

**Comment by mcolour** [comment]
Actually try deleting pvpcomprankpanel.res and see how it goes

**Comment by mcolour** [comment]
Please

**Comment by AaRCaT** [comment]
Okay, i will check out

**Comment by AaRCaT** [comment]
Nope, don't work

**Comment by mcolour** [comment]
Try this
[pvpcomprankpanel.txt](https://github.com/mcolour/colourhud/files/12305550/pvpcomprankpanel.txt)

**Comment by AaRCaT** [comment]
don't work :(

**Comment by mcolour** [comment]
Well I think that the comp rank model in match summary can't be changed, since it didn't work with pvpcomprankpanel.res removed, which forced TF2 to use the default one. But I might be wrong here. 
Sorry :/
